### ISSUE TITLE
Variables in contest's repos

### ISSUE THREAD

**Issue by ViCt0r99** [LowerSilesians/brightway#1]
Hello @cmutel, I have some question regarding the contest libraries, I was looking at the code and found some issues related to the variables that are not defined for instance in Database Explorer (temporary name as team didn't pick any in GitHub issue): https://github.com/Depart-de-Sentier/visualization-contest-2022/issues/8, like:
- `CA_Elem_Flow`,
- `CA_Process`.
Do you have any clue what exactly they should have been?

**Comment by cmutel** [comment]
@ViCt0r99 Well, there is a reason we need some professionals to clean up the code :) 

Without some input from @RomainBes we are blocked for now; I am pretty sure that this is a [contribution analysis](https://github.com/brightway-lca/brightway2-analyzer/blob/main/bw2analyzer/contribution.py#L127) result turned into a Pandas DataFrame, but I can't guess the column labels or datatypes.

**Comment by cmutel** [comment]
@ViCt0r99 Please see the comment in https://github.com/RomainBes/DataVizChallenge/issues/2, it gives this code.

**Comment by ViCt0r99** [comment]
Amazing, thank @cmutel
