### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by ViCt0r99** [LowerSilesians/brightway#3]
Hello @cmutel once again, I'm really sorry to bother You, but I'm trying to perform some testing using your [file](https://github.com/Depart-de-Sentier/visualization-contest-2022/blob/main/Visualization%20fixtures%20creation.ipynb) and [data](https://files.brightway.dev/visualization_example_data.zip) to perform some testing with following command: `jupyter nbconvert --execute creation.ipynb --to python,` but I'm encountering such error: 
```
AttributeError                            Traceback (most recent call last)
Cell In[4], line 1
----> 1 bi.useeio11()

AttributeError: module "bw2io" has no attribute "useeio11"
AttributeError: module "bw2io" has no attribute "useeio11"

```
are you familiar with it? Maybe it's related to version of bw2io library, currently I have `0.8.8` installed?

**Comment by cmutel** [comment]
@ViCt0r99 Sorry for not communicating this more clearly; you need to be using the development version of Brightway (we call it 2.5). So this means the following library versions:

* bw2analyzer >=0.11.4
* bw2calc >=2.0.dev12
* bw2data >=4.0.dev18
* bw2io >=0.9.dev14

You will also need to install `bw_processing` and `matrix_utils`. 

The easiest way to do this is install the `brightway25` package from [anaconda](https://anaconda.org/cmutel/brightway25), but you can also install from pypi with the `--pre` flag.

**Comment by ViCt0r99** [comment]
Okay, thanks for feedback, we updated the requirements based on your comment, now we're encountering next error during run of this [file](https://github.com/Depart-de-Sentier/visualization-contest-2022/blob/main/Visualization%20fixtures%20creation.ipynb):
```
KeyError                                  Traceback (most recent call last)
Cell In[7], line 1
----> 1 df['categories'] = df['categories'].apply(safe_joiner)

File /opt/homebrew/lib/python3.9/site-packages/pandas/core/frame.py:3745, in DataFrame.__getitem__(self, key)
   3743 if self.columns.nlevels > 1:
   3744     return self._getitem_multilevel(key)
-> 3745 indexer = self.columns.get_loc(key)
   3746 if is_integer(indexer):
   3747     indexer = [indexer]

File /opt/homebrew/lib/python3.9/site-packages/pandas/core/indexes/range.py:349, in RangeIndex.get_loc(self, key)
    347         raise KeyError(key) from err
    348 self._check_indexing_error(key)
--> 349 raise KeyError(key)

KeyError: 'categories'
```
Have You ever encountered such issue @cmutel?

**Comment by cmutel** [comment]
`s/df = bd.Database("US EEIO 1.1").nodes_to_dataframe()/df = bd.Database("USEEIO-1.1").nodes_to_dataframe()`
