### ISSUE TITLE
Reference to numpy from pandas

### ISSUE THREAD

**Issue by cmutel** [LowerSilesians/brightway#9]
https://github.com/LowerSilesians/brightway/blob/7f224102b028d3180e2cd463780c16e7f5602cbc/bw_visualization/compare_plot/compare_plot.py#L411

`pd` is pandas, `np` is presumably numpy, this line is broken as is.

**Comment by HamedAkhavan** [comment]
@cmutel fixed it here https://github.com/LowerSilesians/brightway/blob/7abb7e21798f96c00d5e292e69e786712936b61b/bw_visualization/compare_plot/compare_plot.py#L572

PR: https://github.com/LowerSilesians/brightway/pull/8
